services:
  gateway:
    container_name: gateway
    build:
      context: ./backend
      dockerfile: ./cmd/gateway/Dockerfile
    ports:
      - "6500:6500"
    depends_on:
      - attachment
      - attachment_types
      - departments
      - direction
      - history
      - implementors
      - priorities
      - sentence_attachments
      - sentences
      - statuses
    volumes:
      - media-data:/app/media
    networks:
      - sentence-network
    restart: always


  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: sentence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sentence-network
    restart: always

  attachment:
    container_name: attachment
    build:
      context: ./backend
      dockerfile: ./cmd/attachment/Dockerfile
    ports:
      - "6523:6523"
    depends_on:
      - postgres
    volumes:
      - media-data:/app/media
    networks:
      - sentence-network
    restart: always

  attachment_types:
    container_name: attachment_types
    build:
      context: ./backend
      dockerfile: ./cmd/attachmentTypes/Dockerfile
    ports:
      - "6521:6521"
    depends_on:
      - postgres
    networks:
      - sentence-network
    restart: always

  departments:
    container_name: departments
    build:
      context: ./backend
      dockerfile: ./cmd/departments/Dockerfile
    ports:
      - "6519:6519"
    depends_on:
      - postgres
    networks:
      - sentence-network
    restart: always

  direction:
    container_name: direction
    build:
      context: ./backend
      dockerfile: ./cmd/direction/Dockerfile
    ports:
      - "6515:6515"
    depends_on:
      - postgres
    networks:
      - sentence-network
    restart: always

  history:
    container_name: history
    build:
      context: ./backend
      dockerfile: ./cmd/history/Dockerfile
    ports:
      - "6525:6525"
    depends_on:
      - postgres
    networks:
      - sentence-network
    restart: always

  implementors:
    container_name: implementors
    build:
      context: ./backend
      dockerfile: ./cmd/implementors/Dockerfile
    ports:
      - "6517:6517"
    depends_on:
      - postgres
    networks:
      - sentence-network
    restart: always

  priorities:
    container_name: priorities
    build:
      context: ./backend
      dockerfile: ./cmd/priorities/Dockerfile
    ports:
      - "6513:6513"
    depends_on:
      - postgres
    networks:
      - sentence-network
    restart: always

  sentence_attachments:
    container_name: sentence_attachments
    build:
      context: ./backend
      dockerfile: ./cmd/sentenceAttachments/Dockerfile
    ports:
      - "6527:6527"
    depends_on:
      - postgres
    networks:
      - sentence-network
    restart: always

  sentences:
    container_name: sentences
    build:
      context: ./backend
      dockerfile: ./cmd/sentences/Dockerfile
    ports:
      - "6503:6503"
    depends_on:
      - postgres
    networks:
      - sentence-network
    restart: always

  statuses:
    container_name: statuses
    build:
      context: ./backend
      dockerfile: ./cmd/statuses/Dockerfile
    ports:
      - "6511:6511"
    depends_on:
      - postgres
    networks:
      - sentence-network
    restart: always

volumes:
  postgres_data:
  media-data:

networks:
  sentence-network:
    driver: bridge