services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: sentence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: